import { Modal } from './modal.jsx';
import { ModalContainer } from './modal-container.jsx';
import { ModalCard } from './modal-card.jsx';
import { ModalClose } from './modal-close.jsx';
import { ModalBackground } from './modal-background.jsx';
import { ModalOrganizer } from './modal-organizer.jsx';
import { ModalOrganizerIcon } from './modal-organizer-icon.jsx';
import { ModalOrganizerText } from './modal-organizer-text.jsx';
import { ModalOrganizerImage } from './modal-organizer-image.jsx';
import { ModalOrganizerAvatar } from './modal-organizer-avatar.jsx';
import { ModalOrganizerSafe } from './modal-organizer-safe.jsx';
import { ModalFooter } from './modal-footer.jsx';
import { ModalTitle } from './modal-title.jsx';
import { ModalDescription } from './modal-description.jsx';
import { ModalImage } from './modal-image.jsx';
import { ModalAvatar } from './modal-avatar.jsx';

if (!customElements.get('dsh-modal')) customElements.define('dsh-modal', Modal);
if (!customElements.get('dsh-modal-container')) customElements.define('dsh-modal-container', ModalContainer);
if (!customElements.get('dsh-modal-card')) customElements.define('dsh-modal-card', ModalCard);
if (!customElements.get('dsh-modal-close')) customElements.define('dsh-modal-close', ModalClose);
if (!customElements.get('dsh-modal-background')) customElements.define('dsh-modal-background', ModalBackground);
if (!customElements.get('dsh-modal-organizer')) customElements.define('dsh-modal-organizer', ModalOrganizer);
if (!customElements.get('dsh-modal-organizer-icon')) customElements.define('dsh-modal-organizer-icon', ModalOrganizerIcon);
if (!customElements.get('dsh-modal-organizer-text')) customElements.define('dsh-modal-organizer-text', ModalOrganizerText);
if (!customElements.get('dsh-modal-organizer-image')) customElements.define('dsh-modal-organizer-image', ModalOrganizerImage);
if (!customElements.get('dsh-modal-organizer-avatar')) customElements.define('dsh-modal-organizer-avatar', ModalOrganizerAvatar);
if (!customElements.get('dsh-modal-organizer-safe')) customElements.define('dsh-modal-organizer-safe', ModalOrganizerSafe);
if (!customElements.get('dsh-modal-footer')) customElements.define('dsh-modal-footer', ModalFooter);
if (!customElements.get('dsh-modal-title')) customElements.define('dsh-modal-title', ModalTitle);
if (!customElements.get('dsh-modal-description')) customElements.define('dsh-modal-description', ModalDescription);
if (!customElements.get('dsh-modal-image')) customElements.define('dsh-modal-image', ModalImage);
if (!customElements.get('dsh-modal-avatar')) customElements.define('dsh-modal-avatar', ModalAvatar);

export { Modal, ModalContainer, ModalCard, ModalClose, ModalBackground };
export { ModalOrganizer, ModalOrganizerIcon, ModalOrganizerText, ModalOrganizerImage };
export { ModalOrganizerAvatar, ModalOrganizerSafe, ModalFooter };
export { ModalTitle, ModalDescription, ModalImage, ModalAvatar };
