import {
  DshColorPrimaryA6,
  DshColorPrimaryC6,
  DshColorComplementaryR6,
  DshColorComplementaryL6,
  DshColorComplementaryV6,
  DshColorComplementaryT6,
  DshColorSecondaryM6,
  DshColorSecondaryX6,
  DshColorSecondaryG6,
  DshColorComplementaryN6,
  DshColorSecondaryG5,
  DshColorSecondaryG1,
  DshColorSecondaryG2,
  DshColorSecondaryG3,
  DshColorSecondaryG4,
  DshColorPrimaryA3,
  DshColorPrimaryA1,
  DshColorPrimaryC1,
  DshColorPrimaryC3,
  DshColorComplementaryV1,
  DshColorComplementaryV3,
  DshColorComplementaryR1,
  DshColorComplementaryR3,
  DshColorComplementaryL1,
  DshColorComplementaryL3,
  DshColorComplementaryT1,
  DshColorComplementaryT3,
  DshColorSecondaryM1,
  DshColorSecondaryM3,
  DshColorSecondaryX1,
  DshColorSecondaryX3,
  DshColorComplementaryN1,
  DshColorComplementaryN3,
} from '@tokens';

export const itemTokens = {
  color: {
    default: DshColorPrimaryA3,
    v1: DshColorComplementaryV1,
    v3: DshColorComplementaryV3,
    r1: DshColorComplementaryR1,
    r3: DshColorComplementaryR3,
    c1: DshColorPrimaryC1,
    c3: DshColorPrimaryC3,
    c6: DshColorPrimaryC6,
    l1: DshColorComplementaryL1,
    l3: DshColorComplementaryL3,
    a1: DshColorPrimaryA1,
    a3: DshColorPrimaryA3,
    a6: DshColorPrimaryA6,
    t1: DshColorComplementaryT1,
    t3: DshColorComplementaryT3,
    t6: DshColorComplementaryT6,
    m1: DshColorSecondaryM1,
    m3: DshColorSecondaryM3,
    m6: DshColorSecondaryM6,
    x1: DshColorSecondaryX1,
    x3: DshColorSecondaryX3,
    x6: DshColorSecondaryX6,
    n1: DshColorComplementaryN1,
    n3: DshColorComplementaryN3,
    n6: DshColorComplementaryN6,
    g1: DshColorSecondaryG1,
    g2: DshColorSecondaryG2,
    g3: DshColorSecondaryG3,
    g4: DshColorSecondaryG4,
    g5: DshColorSecondaryG5,
    g6: DshColorSecondaryG6,
    v6: DshColorComplementaryV6,
    r6: DshColorComplementaryR6,
    l6: DshColorComplementaryL6,
  },
};
