import {
  DshColorSecondaryG1,
  DshColorSecondaryG2,
  DshColorSecondaryG3,
  DshColorMonoWhite,
  DshColorMonoBlack,
  DshColorPrimaryC0,
  DshColorPrimaryC1,
  DshColorPrimaryC2,
  DshColorPrimaryC3,
  DshColorSecondaryM2,
  DshColorComplementaryR1,
  DshColorComplementaryR2,
  DshColorPrimaryA1,
  DshColorPrimaryA6,
  DshColorComplementaryV1,
  DshColorSecondaryX1,
  DshColorSecondaryX2,
  DshColorSecondaryX3,
  DshColorSecondaryX4,
  DshColorSecondaryX6,
  DshColorComplementaryT1,
  DshColorComplementaryL2,
  DshColorComplementaryL3,
  DshColorComplementaryN1,
} from '@tokens';

export const colorTokens = {
  slate: `${DshColorSecondaryG1}`,
  blue: `${DshColorPrimaryC2}`,
  purple: `${DshColorSecondaryM2}`,
  white: `${DshColorMonoWhite}`,
  black: `${DshColorMonoBlack}`,
  negro: `${DshColorMonoBlack}`,
  g1: `${DshColorSecondaryG1}`,
  g2: `${DshColorSecondaryG2}`,
  g3: `${DshColorSecondaryG3}`,
  c0: `${DshColorPrimaryC0}`,
  c1: `${DshColorPrimaryC1}`,
  c2: `${DshColorPrimaryC2}`,
  c3: `${DshColorPrimaryC3}`,
  r1: `${DshColorComplementaryR1}`,
  r2: `${DshColorComplementaryR2}`,
  a1: `${DshColorPrimaryA1}`,
  a6: `${DshColorPrimaryA6}`,
  v1: `${DshColorComplementaryV1}`,
  x1: `${DshColorSecondaryX1}`,
  x2: `${DshColorSecondaryX2}`,
  x3: `${DshColorSecondaryX3}`,
  x4: `${DshColorSecondaryX4}`,
  x6: `${DshColorSecondaryX6}`,
  t1: `${DshColorComplementaryT1}`,
  m1: `${DshColorSecondaryM2}`,
  l2: `${DshColorComplementaryL2}`,
  l3: `${DshColorComplementaryL3}`,
  n1: `${DshColorComplementaryN1}`,
  current: 'currentColor',
};

export const sizeTokens = {
  s1: '16px',
  s2: '24px',
  s3: '32px',
  s4: '40px',
  s5: '48px',
  s6: '56px',
  s7: '64px',
};

export const fontTokens = {
  s1: '8px',
  s2: '16px',
  s3: '24px',
  s4: '32px',
  s5: '40px',
  s6: '48px',
  s7: '56px',
};
